### ISSUE TITLE
url encoded page[number] and page[size]

### ISSUE THREAD

**Issue by ruckc** [mu-semtech/ember-data-table#10]
According to jsonapi.org/format/

> Note: The example query parameters above use unencoded [ and ] characters simply for readability. In practice, these characters must be percent-encoded, per the requirements in RFC 3986.

The `page[number]` and `page[size]` parameters should be url encoded.  In serializer.js it assumes the `page[number]` and `page[size]` are not url encoded.

I believe the right answer would be to add an `|| param === 'page%5Bnumber%5D'` or urldecode the parameter before comparing.

**Comment by erikap** [comment]
@ruckc Thanks for the suggestion. Feel free to create a PR to fix this.

**Comment by erikap** [comment]
Resolved by #14
