### ISSUE TITLE
Sorting arrows (asc desc) not showiing

### ISSUE THREAD

**Issue by hsduiii** [mu-semtech/ember-data-table#18]
![image](https://user-images.githubusercontent.com/37885943/62592636-873deb80-b899-11e9-9d80-a4b1ac26b60e.png)

**Comment by erikap** [comment]
Hi @hsduiii, this addon indeed doesn't have arrows for sorting. It just shows 'asc' en 'desc' in front of the column names. You have the options to add styling in your host app (using CSS or by overwriting the addons template file) or to use a styled extension of this addon (e.g. https://github.com/mu-semtech/ember-paper-data-table)

**Comment by hsduiii** [comment]
> Hi @hsduiii, this addon indeed doesn't have arrows for sorting. It just shows 'asc' en 'desc' in front of the column names. You have the options to add styling in your host app (using CSS or by overwriting the addons template file) or to use a styled extension of this addon (e.g. https://github.com/mu-semtech/ember-paper-data-table)

**Comment by hsduiii** [comment]
Oh, i see, thanks!
