### ISSUE TITLE
The full `lodash` library is included

### ISSUE THREAD

**Issue by Windvis** [mu-semtech/ember-data-table#28]
It seems like this addon imports lodash (through ember-lodash) to merge objects together.

The problem is that the full lodash library is included instead of only that specific function. This increases the bundle size by _a lot_.

Some build size comparisons:

**Production build of a newly generated Ember app.**
```
File sizes:
 - dist/assets/data-table-test-2433f9de99b639ee070d99e9db936375.js: 8.43 KB (1.71 KB gzipped)
 - dist/assets/data-table-test-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/assets/vendor-423cd95bd84c864cb098d7ad30d295c6.js: 698.86 KB (186.17 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```
**Production build of the same app, after installing this addon**
```
File sizes:
 - dist/assets/data-table-test-1bb3a0fc21b16df67fbd5fddc371dda2.js: 42.2 KB (3.7 KB gzipped)
 - dist/assets/data-table-test-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/assets/vendor-678fbf24ed0f76c2b3ba0b455641a2bb.js: 1.04 MB (243.89 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 ```
It's hard to determine from an app how the lodash dependency increases the bundle size, but [bundlephobia can give us some insights](https://bundlephobia.com/package/lodash@4.17.21).

Switching to ember-auto-import and importing only the specific function should treeshake the unused ones out. Alternatively we can simply not use lodash for this and write the merge util ourselves.

**Comment by aatauil** [comment]
Alternatively (If I am not mistaking), it should be possible to only install modules of lodash you need e.g. https://www.npmjs.com/package/lodash.groupby.

**Comment by Windvis** [comment]
@aatauil Yup! It would still require ember-auto-import to import them though. And I seem to recall a conversation in the rocket chat where it was mentioned that those individual module aren't recommended (anymore)?
