### ISSUE TITLE
materialize stylesheet does not exist, same for variables in $table-border-color etc in ember-data-table.scss

### ISSUE THREAD

**Issue by theseyi** [mu-semtech/ember-data-table#5]
```css
// Materialize styles
@import "materialize";

.data-table-header {
    border-bottom: 1px solid $table-border-color;
    padding: 10px 5px;
    color: $secondary-color;

    .btn-flat {
        color: $secondary-color;
    }`

The style above generate error when compilation is attempted during build

**Comment by erikap** [comment]
Hi @theseyi, which version of ember-data-table and ember-cli do you use?
Did you install the addon using the `ember install ember-data-table` command?

**Comment by theseyi** [comment]
Hi @erikap 
`
ember-cli: 2.10.0
node: 7.4.0
os: darwin x64`
 and for ember-data-table 0.6.0

I think the issue is that the peer dep of `ember-cli-materialize` is not installed when `ember install ember-data-table` is run. I had to install that manually and a few other dependencies to get it to work. However, after I got it running, the column sort failed to function. I passed is the table content as an array of objects 
````javascript

    {firstName: 'John', lastName: 'Doe', age: 20, created: Date.now(), modified: Date.now()},
    {firstName: 'Jane', lastName: 'Doe', age: 25, created: Date.now(), modified: Date.now()},
````
but the actual column sorting feature was not functional.

**Comment by erikap** [comment]
Hi @theseyi, the missing peer dependency of `ember-cli-materialize` was also what I was thinking. But normally, it should be automatically installed after installing `ember-data-table` as defined in the [index.js blueprint](https://github.com/mu-semtech/ember-data-table/blob/master/blueprints/ember-data-table/index.js#L15). 

I tried to reproduce your issue by installing the `ember-data-table` addon in a new ember project, but `ember-cli-materialize` is automatically installed as expected.

**Comment by theseyi** [comment]
Hmm.. are you running same version of node? `v7.4.0` and also npm `3.8.6`?

If so I guess you can close this as it maybe an isolated incident.

**Comment by theseyi** [comment]
@erikap Have you tried to clone the repo in a new directory and run `ember install`?
````bash
Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Class.<anonymous> (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:117:26)
    at Array.map (native)
    at Class.CoreObject.extend.discoverFromDependencies (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:107:70)
    at Class.CoreObject.extend.discoverChildAddons (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:69:33)
    at Class.CoreObject.extend.discoverAddons (/usr/local/lib/node_modules/ember-cli/lib/models/addon.js:218:42)
    at Class.CoreObject.extend.initializeAddons (/usr/local/lib/node_modules/ember-cli/lib/models/addon.js:231:10)
    at setupRegistryForEachAddon (/usr/local/lib/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/usr/local/lib/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)
````

**Comment by erikap** [comment]
@theseyi If you clone the repo, you first have to run `npm install && bower install` before you can run `ember server`.

**Comment by erikap** [comment]
@theseyi I was able to reproduce your issue. Apparently running `ember install ember-cli-materialize` manually doesn't have the same effect as installing it in the `afterInstall` hook of the addon's blueprint. E.g. the materialize bower package isn't installed using the hook.

I will have a closer look, but for now, as a workaround, you can just run `ember install ember-cli-materialize` after installing the ember-data-table addon. I will update the README accordingly.
