### ISSUE TITLE
Error: Error: argument `$map1` of `map-merge($map1, $map2)` must be a map

### ISSUE THREAD

**Issue by blackode** [mu-semtech/ember-data-table#6]
When I try to install, It asked me to override the `app.scss` I have chosen `n` option No        

Please refer the following screenshot

![screenshot from 2017-11-27 18-16-35](https://user-images.githubusercontent.com/9107477/33267371-3eb7d974-d39f-11e7-8f84-922c61be47ca.png)

**Comment by erikap** [comment]
Hi @blackode, did you add the following lines to your `app.scss` file?

```
@import 'ember-paper';
@import 'ember-data-table';
```

The ember-paper addon should also be installed by running the command:
```
ember install ember-paper
```

**Comment by blackode** [comment]
@erikap 
Thanks for quick response. 
Yes, I installed and added both of them
Here I am attaching the screenshot.
![screenshot from 2017-11-28 14-33-21](https://user-images.githubusercontent.com/9107477/33310899-2b5d571e-d449-11e7-9fb7-d7db8525c5c0.png)

**Comment by blackode** [comment]
## ember -v
```js
ember-cli: 2.16.2
node: 8.9.1
os: linux x64
```
```diff
### app/styles/app.scss
+ @import 'ember-paper';
+ @import 'ember-data-table';
```

**Comment by blackode** [comment]
@erikap I recorded the process of Installation. So, it helps you to help me. 
Thanks       

### Record
https://asciinema.org/a/149853

**Comment by erikap** [comment]
@blackode The error originates from ember-paper. The message implies that the SASS variable `$color-grey` isn't a map, while the variable is initialized as a map by ember-paper: https://github.com/miguelcobain/ember-paper/blob/5f599360b89667f4fc8fa236f20441610e7ff067/app/styles/color-palette.scss#L408

So it seems to me that one of your `@import` statements before `@import 'ember-paper'` in your `app.scss`  overwrites this variable with another value than a map. Can you try to move the `@import 'ember-paper'` to the top of the file and validate whether you still get the same error message?

**Comment by blackode** [comment]
Sure I will let you know

**Comment by blackode** [comment]
I found this note in the `ember-paper`. This solved the issue.      

**Note**: If upgrading from a previous version of` ember-paper` and you are seeing compile errors around `app.scss|sass` not existing, please make sure to remove **`broccoli-sass`** from your package.json, remove your `node_modules `and reinstall.  

**Thank you.** @erikap
