### ISSUE TITLE
Source code for demo app

### ISSUE THREAD

**Issue by abdullah2891** [mu-semtech/ember-data-table#7]
It would be helpful you could provide the source code for the demo app. I have seen the code samples, but I would be able to see the whole project and understand how everything ties together

**Comment by erikap** [comment]
Hi @abdullah2891, the source code of the demo app is available at https://github.com/erikap/ember-data-table-demo. I will add a link to the source repository in the app. Thanks for the tip!

**Comment by erikap** [comment]
Source code of the demo app is now available at https://github.com/erikap/ember-paper-data-table-demo. A link to the source code is added to the demo pages.
