### ISSUE TITLE
Size and other filtering not working

### ISSUE THREAD

**Issue by tri003** [mu-semtech/ember-data-table#9]
Not Changing display when size and other filtering action.

can i use this route?

import Route from '@ember/routing/route';
import DataTableRouteMixin from 'ember-data-table/mixins/route';

export default Route.extend(DataTableRouteMixin,{
model(){
    return [
            {
                'id':'1',
                'firstName':'sample',
                'lastName':'sampl',
                'age':'24',
                'created':'now',
                'modified':'later',
            },
            {
                'id':'2',
                'firstName':'sample',
                'lastName':'sample',
                'age':'24',
                'created':'now',
                'modified':'later',
            },
            {
                'id':'3',
                'firstName':'sample',
                'lastName':'sample',
                'age':'24',
                'created':'now',
                'modified':'later',
            },
            {
                'id':'4',
                'firstName':'sampler',
                'lastName':'sample',
                'age':'24',
                'created':'now',
                'modified':'later',
            },
            {
                'id':'5',
                'firstName':'sample',
                'lastName':'sample',
                'age':'24',
                'created':'now',
                'modified':'later',
            },
        ];
}

});

**Comment by erikap** [comment]
The `DataTableRouteMixin` implements the model hook and configures the query params `filter`, `page`, `size` and `sort` to trigger a model refresh on change. Since you're overwriting the `model()` hook in your route to always return the same fixed array of data you won't see any changes.
